block_type: paragraph
concepts:
- Λ
- λ
excerpt: 'Λ(T(MN))=Λ(eval(T(M),T(N)))=Λ(T(M))Λ(T(N))=MN Λ(T(MN))=Λ(eval(T(M),T(N)))=Λ(T(M))Λ(T(N))=MN
  Thus:'
heading: 'For application:'
id: GEN17-4511
lines: 5821-5830
location: genesis-17/box-calculus::4-the-heart-of-the-equivalence::41-λ-box-λ-gives-the-same-λ-term::for-application::b1
parent_heading: 4.1 λ → Box → λ gives the same λ-term
source: genesis-17\box_calculus.md
